# Generated by Django 4.2.5 on 2024-02-10 01:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0003_alter_item_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='is_hired',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=4000, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_requests/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=4000, null=True)),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='equipment_requests/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.equipmentcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
