# Generated by Django 4.2.5 on 2024-02-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_equipmentcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='available_for_hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
