# Generated by Django 4.2.5 on 2024-02-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_equipment_description_hirerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='pdf_idCopy',
            field=models.FileField(blank=True, null=True, upload_to='hire_requests/documents/'),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='pdf_other',
            field=models.FileField(blank=True, null=True, upload_to='hire_request/documents/'),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='pdf_proof_of_residence',
            field=models.FileField(blank=True, null=True, upload_to='hire_request/documents/'),
        ),
    ]
