# Generated by Django 4.2.5 on 2024-02-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_hirerequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='next_of_kin_contact',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='province',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='suburb',
        ),
    ]
