# Generated by Django 4.2.5 on 2024-02-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_hirerequest_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('INCOMPLETE', 'Incomplete')], default='INCOMPLETE', max_length=10),
        ),
    ]
