# Generated by Django 4.2.5 on 2024-02-12 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0011_alter_equipmentcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
