# Generated by Django 4.2.5 on 2024-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_hirerequest_farmer_hirerequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
