# Generated by Django 4.2.5 on 2024-01-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqcard',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='faqcard',
            name='user_name',
        ),
        migrations.AddField(
            model_name='faqcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faq_images/'),
        ),
    ]
