# Generated by Django 4.2.5 on 2024-01-27 02:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_faqcard_image_url_remove_faqcard_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcard',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
    ]
