# Generated by Django 4.2.5 on 2024-01-27 02:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_faqcard_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcard',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True),
        ),
    ]
