# Generated by Django 4.2.5 on 2024-01-27 19:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_faqcard_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcard',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, max_length=4000, null=True),
        ),
    ]
