# Generated by Django 4.2.5 on 2024-01-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='farmers',
            new_name='farmer',
        ),
    ]
