# Generated by Django 4.2.5 on 2024-01-24 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0002_equipmentcategory_equipment'),
        ('chat', '0002_rename_farmers_chat_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_chat', to='item.equipment')),
                ('hirer', models.ManyToManyField(related_name='equipment_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_equipment_messages', to=settings.AUTH_USER_MODEL)),
                ('equipment_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_chat_message', to='chat.equipmentchat')),
            ],
        ),
    ]
