# Generated by Django 4.2.5 on 2024-01-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_equipmentchat_equipmentchatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentchat',
            old_name='hirer',
            new_name='farmer',
        ),
    ]
