# Generated by Django 5.0.1 on 2024-02-15 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_complete', models.BooleanField(default=False)),
                ('profile_public', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='forum/badges')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pictures\\default_profile.png', upload_to='profile_pictures')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('suburb', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, choices=[('Gauteng', 'Gauteng'), ('Eastern Cape', 'Eastern Cape'), ('Limpopo', 'Limpopo'), ('Western Cape', 'Western Cape'), ('North West', 'North West'), ('Mpumalanga', 'Mpumalanga'), ('Free State', 'Free State'), ('Northern Cape', 'Northern Cape'), ('Kwa-Zulu Natal', 'Kwa-Zulu Natal')], max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('Herding', 'Herding'), ('Mixed', 'Mixed'), ('Crop Farming', 'Crop Farming')], max_length=30, null=True)),
                ('farming_practices', models.CharField(choices=[('Sustainable Farming', 'Sustainable Farming'), ('Organic Farming', 'Organic Farming'), ('Regenarative Farming', 'Regenarative Farming'), ('Precision Farming', 'Precision Farming'), ('Permaculture', 'Permaculture'), ('Conventional Farming', 'Conventional Farming'), ('No-Till Farming', 'No-Till Farming'), ('Hydroponics & Aquaponics', 'Hydroponics & Aquaponics')], max_length=30)),
                ('crops_grown', models.CharField(blank=True, max_length=255, null=True)),
                ('livestock_grown', models.CharField(blank=True, max_length=255, null=True)),
                ('farming_specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('certification', models.CharField(blank=True, max_length=255, null=True)),
                ('farming_experience', models.IntegerField(blank=True, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('info_filled', models.BooleanField(default=False)),
                ('expertise', models.ManyToManyField(to='accounts.expertise')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
