# Generated by Django 5.0.1 on 2024-02-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='province',
            field=models.CharField(blank=True, choices=[('Gauteng', 'Gauteng'), ('Northern Cape', 'Northern Cape'), ('Limpopo', 'Limpopo'), ('Western Cape', 'Western Cape'), ('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Kwa-Zulu Natal', 'Kwa-Zulu Natal'), ('North West', 'North West'), ('Mpumalanga', 'Mpumalanga')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farminfo',
            name='farming_practices',
            field=models.CharField(choices=[('Organic Farming', 'Organic Farming'), ('Precision Farming', 'Precision Farming'), ('No-Till Farming', 'No-Till Farming'), ('Conventional Farming', 'Conventional Farming'), ('Sustainable Farming', 'Sustainable Farming'), ('Permaculture', 'Permaculture'), ('Regenarative Farming', 'Regenarative Farming'), ('Hydroponics & Aquaponics', 'Hydroponics & Aquaponics')], max_length=30),
        ),
        migrations.AlterField(
            model_name='farminfo',
            name='industry',
            field=models.CharField(blank=True, choices=[('Crop Farming', 'Crop Farming'), ('Herding', 'Herding'), ('Mixed', 'Mixed')], max_length=30, null=True),
        ),
    ]
