# Generated by Django 5.0.1 on 2024-02-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_additionalinfo_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='province',
            field=models.CharField(blank=True, choices=[('Free State', 'Free State'), ('North West', 'North West'), ('Gauteng', 'Gauteng'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('Eastern Cape', 'Eastern Cape'), ('Kwa-Zulu Natal', 'Kwa-Zulu Natal'), ('Northern Cape', 'Northern Cape'), ('Western Cape', 'Western Cape')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farminfo',
            name='farming_practices',
            field=models.CharField(choices=[('Permaculture', 'Permaculture'), ('No-Till Farming', 'No-Till Farming'), ('Sustainable Farming', 'Sustainable Farming'), ('Conventional Farming', 'Conventional Farming'), ('Precision Farming', 'Precision Farming'), ('Hydroponics & Aquaponics', 'Hydroponics & Aquaponics'), ('Regenarative Farming', 'Regenarative Farming'), ('Organic Farming', 'Organic Farming')], max_length=30),
        ),
    ]
