# Generated by Django 4.2.5 on 2024-02-08 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency', '0003_designatedcontact_emergencyservice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignatedContact',
        ),
        migrations.DeleteModel(
            name='EmergencyService',
        ),
        migrations.RenameField(
            model_name='soscall',
            old_name='additional_details',
            new_name='additional_info',
        ),
        migrations.RemoveField(
            model_name='soscall',
            name='emergency_type',
        ),
        migrations.RemoveField(
            model_name='soscall',
            name='location',
        ),
        migrations.RemoveField(
            model_name='soscall',
            name='user_contact',
        ),
        migrations.RemoveField(
            model_name='soscall',
            name='user_name',
        ),
        migrations.AddField(
            model_name='soscall',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
