"""
Django settings for Alpha project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import django_heroku
import dj_database_url
from django.contrib.messages import constants as messages
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3dym6r=1qe*_az0*y(bo^x*12kj5@$g8&g218p&5yc3a$$p=c5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['saving-pika-grand.ngrok-free.app', 'localhost', '127.0.0.1']

STRIPE_PUB_KEY = 'pk_test_51NsFmAEuJhOtyzrqlIsKiN83EUnqZaLyn2XuGodozoGzj7xSdaxz1lPFRt5dVq4pzRFFCDBgWH0i0slpvawn7Ocs00lM3eFRou'
STRIPE_SECRET_KEY = 'sk_test_51NsFmAEuJhOtyzrq4tjet67pJE5EsWWi1kMjrbrubbmGhdeVBvsEZfHA9G3SaQz75L4a4DtLPYoM70BUVL4H2QhF00rpiwYRlW'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mmatladikatlego5@gmail.com'
EMAIL_HOST_PASSWORD = 'fzwikrwmcxumcdtd'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Application definition

SESSION_COOKIE_AGE = 86400
CART_SESSION_ID = 'cart'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'ckeditor',
    'ckeditor_uploader',
    'taggit',
    'noticeboard',
    'accounts',
    'forum',
    'marketplace',
    'item',
    'dashboard',
    'chat',
    'cart',
    'order',
    'weather',
    'core',
    'allauth', 
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'emergency',
    'hire',
]

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]



ROOT_URLCONF = 'Alpha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Format', 'Styles'],
            ['Bold', 'Italic', 'Underline'],
            ['Link', 'Unlink'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['HorizontalRule'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord'],
            ['Maximize'],
            ['Image', 'ImageResizeEditing', 'ImageResizeHandles'],
            ['UploadImage'],
        ],
        'extraPlugins': ','.join(['image2', 'imageresize']),
        'height': 300,
        'autoGrow_bottomSpace': 10,
        'autoGrow_topSpace': 10,
    },
}

WSGI_APPLICATION = 'Alpha.wsgi.application'

AUTH_USER_MODEL = 'accounts.BasicAccount'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True

LOGIN_REDIRECT_URL = 'home'
ACCOUNT_SIGNUP_REDIRECT_URL = 'edit_profile'
LOGIN_URL = 'login'
ACCOUNT_ADAPTER = 'accounts.adapter.AccountAdapter'
SOCIALACCOUNT_LOGIN_ON_GET = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_UPLOAD_PATH = 'posts/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 2
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        "APP":{
            "client_id": '22575084743-sgatrf0gmadah45njkec2ifuglebqd7r.apps.googleusercontent.com',
            "secret": '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',
            "key": ""
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
]

CSRF_TRUSTED_ORIGINS = ['https://saving-pika-grand.ngrok-free.app', 'https://alphaharvest-5.azurewebsites.net']

django_heroku.settings(locals())
